function diffusion_versus_STDdisplacement(fileSave,Dfit)
%CREATEFIGURE(DFIT1,DFIT2)
%  DFIT1:  vector of x data
%  DFIT2:  vector of y data

%  Auto-generated by MATLAB on 24-Oct-2019 11:00:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 max(Dfit(:,4))+50]);
xlim(axes1,[0 max(Dfit(:,1))+0.2]);

box(axes1,'on');
hold(axes1,'all');
% lbl_dwn = .1*max(Dfit(:,4));
% Create plot
for i=1:size(Dfit,1)
    plot(Dfit(i,1),Dfit(i,4),'MarkerFaceColor',[0 0 1],'MarkerSize',10,'Marker','o',...
    'LineStyle','none');
%text(Dfit(i,1),Dfit(i,4),num2str(Dfit(i,6)),'VerticalAlignment','top','HorizontalAlignment','left','FontWeight','bold','FontSize',14)
end


% Create xlabel
xlabel('Diffusion ( \mum^2/s)','FontSize',20);

% Create ylabel
ylabel('STD displacement (nm)','FontSize',20);

filename = sprintf('%splot_diff.png', fileSave); 
saveas(figure1,filename)
filename = sprintf('%splot_diff.fig',fileSave); 
saveas(figure1,filename)
