function plot_track_nice(X1, Y1, X2, Y2, X3, Y3,figure1)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 10-Oct-2019 10:35:46

% Create axes
axes1 = axes('Parent',figure1,'PlotBoxAspectRatio',[1 1 1],'FontSize',30,...
    'FontName','Calibri');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 max(X1)+50]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 max(Y1)+50]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerEdgeColor',[0 0 1],'MarkerSize',10,'Marker','o',...
    'LineWidth',4,...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'MarkerFaceColor',[1 1 1],'MarkerEdgeColor',[0 1 0],...
    'MarkerSize',15,...
    'Marker','o',...
    'LineWidth',3,...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X3,Y3,'MarkerFaceColor',[1 1 1],'MarkerEdgeColor',[1 0 0],...
    'MarkerSize',15,...
    'Marker','o',...
    'LineWidth',3,...
    'LineStyle','none',...
    'Color',[0 0.5 0]);

% Create xlabel
xlabel('Position x (nm)','FontSize',30,'FontName','Calibri');

% Create ylabel
ylabel('Position y (nm)','FontSize',30,'FontName','Calibri');

