function [inputData] = import_files(filecoords,filecounts,ImageStr)
%This function Import the text files to MatLab
%% INPUT:
%Both input files are generated by rapidStorm. 
%filecoords: has 8 columns: x, y, frame,intensity, PSF in x, PSF in
%y,residue, local background. Data is presented for all particles in one
%frame from the initial frame until the last one. 
%filecounts:the number of localizations on each frame.

%% OUTPUT: 
%A structure array called inputData with the fields: 
%x: vector with all localizations x position for each frame in the
%sequence.
%y: vector with all localizations y position for each frame in the
%sequence.
%framevt: vector with the frame number of each localization
%intensity: vector with intensities for all localizations on every frame in the
%sequence.
%PSFX: vector with PSF in x direction for all localizations on every frame
%in the sequence.
%PSFY: vector with PSF in y direction for all localizations on every frame
%in the sequence.
%residuest: vector with residue in the position fitting for all localizations on every frame
%in the sequence.
%bg: vector with intensity background for all localizations on every frame
%in the sequence.
%counts: vector with the number of localizations per frame. 

%% Created by: CVS On June 27/2018 

%% Edited by:
%1. CVS 2018.07.10 - Separated importing files
%2. CVS 2019.06.27 - Change output to be a structure array

%% Variables Setup
inputData=struct;
inputDataValid=struct;

%% Execution
[inputData] = importloca(filecoords); %import localizations files
[inputData.counts]=importcounts(filecounts); %import counts per frame file
inputData.fileCounts=filecounts;
inputData.fileLocalization=filecoords;

if ImageStr.nframes<ImageStr.NumberImages
    countsBefore=sum(inputData.counts(1:ImageStr.initialFr,2));
    countsValid=sum(inputData.counts(ImageStr.initialFr+1:ImageStr.finalFr+1,2));
    countsFinal=countsBefore+countsValid;
    inputDataValid.x = inputData.x(countsBefore+1:countsFinal,1);
    inputDataValid.y = inputData.y(countsBefore+1:countsFinal,1);
    inputDataValid.frame = inputData.frame(countsBefore+1:countsFinal,1);
    inputDataValid.Amplitud = inputData.Amplitud(countsBefore+1:countsFinal,1);
    inputDataValid.FWHMx = inputData.FWHMx(countsBefore+1:countsFinal,1);
    inputDataValid.FWHMy = inputData.FWHMy(countsBefore+1:countsFinal,1);
    inputDataValid.residueFitting = inputData.residueFitting(countsBefore+1:countsFinal,1);
    inputDataValid.background = inputData.background(countsBefore+1:countsFinal,1);
    inputDataValid.counts=inputData.counts(ImageStr.initialFr+1:ImageStr.finalFr+1,1:2);
    inputData=inputDataValid;
end



end

